require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
install! 'cocoapods', :deterministic_uuids => false



target 'PatientEngagement' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_flipper!({ 'Flipper' => '0.136.0' })

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  pod 'rn-fetch-blob',
    :path => '../node_modules/rn-fetch-blob'
  # pod 'react-native-camera', 
  # path: '../node_modules/react-native-camera', 
#   subspecs: [
#   'TextDetector',
#   'FaceDetectorMLKit',
#   'BarcodeDetectorMLKit'
# ]
  # pod 'react-native-camera', 
  # path: '../node_modules/react-native-camera'

  pod 'TextToSpeech', :path => '../node_modules/react-native-tts'
  # pod 'Firebase', :modular_headers => true
  # pod 'FirebaseCoreInternal', :modular_headers => true
  # pod 'GoogleUtilities', :modular_headers => true

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNCallKeep', :path => '../node_modules/react-native-callkeep'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'react-native-restart', :path => '../node_modules/react-native-restart'

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'
  # pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

  target 'PatientEngagementTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    # Build Active Architecture Only "NO" (react-native-maps)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      end
    end
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
  # pod 'react-native-fbsdk-next', :path => '../node_modules/react-native-fbsdk-next'
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  pod 'RNVoipPushNotification', :path => '../node_modules/react-native-voip-push-notification'
end
